#!/bin/bash

up() {
  if   [[ "${#}" -eq 0 ]]
  then
    cd ".."
  elif [[ "${1}" -gt 0 ]] > "/dev/null" 2>&1
  then
    for i in $(seq "${1}")
    do
      cd ".."
    done
  else
    echo "Error: up should be called with the number of directories to go up. Default is 1."
  fi
}

export -f "up"

mkcd() {
  mkdir --parents "${1}" && cd "${1}"
}

export -f "mkcd"
