#!/bin/bash

clear

echo -e "Hi, ${USER}.\n"

source "${XDG_CONFIG_HOME}/bash/variables"
source "${XDG_CONFIG_HOME}/bash/functions"

transmission-daemon                                                &&
  echo "transmission-daemon started, we'll wait for connection..." ||
  echo "unable to run transmission-daemon!"
