#!/bin/bash

# One can't execute a single script sections separately e.g. as root and
# non-root user, so there should be a master script which will start
# multiple scripts for multiple users.
#
# Another way is root-only script which will change the attributes (such
# as owner and permissions) for different users, but I've found it too
# complicated after a while.
#
# One have to specify a user as 1st positional argumant to start master
# script correctly.

set -e
cd "$(dirname $0)"

source "settings"

for i in $(ls "scripts/${1}")
do
  echo "Executing ${i} ..."
  source "scripts/${1}/${i}"
done
unset i

exit 0
