#!/bin/bash

authorize() {
  echo "Please enter a password for \"${1}\" to perform \"${2}\"."
  until su --login "${1}" --command "${2}"
  do
    echo "   Something gone wrong."
    echo "   Please enter a password for \"${1}\" to perform \"${2}\" once more"
    echo "   or press Ctrl+C to exit this script."
  done
}

authorize "root" "${PWD}/master \"root\""
authorize "user" "${PWD}/master \"user\""
