#!/bin/sh

bspc monitor --reset-desktops "1" "2" "3" "4" "5" "6" "7" "8" "9"

bspc config border_width 4
bspc config window_gap   4
bspc config split_ratio  0.50

bspc config normal_border_color   "#b6c2c3"
bspc config focused_border_color  "#597b9e"
bspc config presel_feedback_color "#597b9e"

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

xrdb -merge "${XDG_CONFIG_HOME}/xorg/xresources"

sxhkd                                                            &
polybar "${ODG_PLATFORM}"                                        &
nm-applet                                                        &
compton --daemon                                                 &

randomwall                                                       &

